config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    confirmations: "users/confirmations",
    sessions: "users/sessions",
    registrations: "users/registrations"
  }, skip: [:passwords]
  devise_scope :user do
    get   '/users/change_email',      to: 'users/registrations#change_email'
    get   '/users/change_password',   to: 'users/registrations#change_password'
    get   '/users/company',           to: 'users/sessions#company'
    post  '/users/company_verify',    to: 'users/sessions#company_verify'
    post  '/companies/admins',        to: 'companies/admins#create',  as: :companies_admins
    get   '/companies/:token/admin',  to: 'companies/admins#new',     as: :new_companies_admin
  end

  namespace :api do
    resource :currency, only: [:show], controller: 'currency'
  end

  # With subdomain constraint
  # -----------------------------------------
  constraints(CompanyConstraint) do
    devise_for :users, controllers: {
      passwords: "users/passwords"
    }, skip: [:registrations, :sessions, :confirmations]

    scope module: 'private', as: :company do
      namespace :admin do
        resources :forms,             except: [:show]
        resources :embedded_forms,    only: [:index, :new, :create, :destroy]
        resource  :plan_and_billings, controller: 'plan_and_billings',  only: [:show, :create] do
          collection do
            put :change_plan
          end
        end
        resource  :billing_address,   controller: 'billing_address',    only: [:update]
        resources :credit_cards,      controller: 'credit_cards',       only: [:create, :destroy]
        root to: 'forms#index'
      end

      concern :trackable do
        resources :public_activity_activities, :path => 'activities', controller: 'activities', :only => [:create]
      end

      resources :form_entries, path: '/tasks', :concerns => :trackable do
        collection do
          get :all
        end

        member do
          # delete attachment
          delete  'destroy_attachment/:field_id', to: 'form_entries#destroy_attachment',    as: :destroy_attachment
          delete  'destroy_expense_attachment/:field_id/row/:row_index/index/:file_index',  to: 'form_entries#destroy_expense_attachment', as: :destroy_expense_attachment

          # upload attachment
          # post    'upload_attachment/:field_id',  to: 'form_entries#upload_attachment',     as: :upload_attachment
          post    'upload_expense_attachment/:field_id/row/:row_index',   to: 'form_entries#upload_expense_attachment', as: :upload_expense_attachment

          # change status
          put     'change_status/:status',        action: :change_status,                   constraints: { status: /cancel|approve|/ }, as: :change_status
        end
      end

      resources :timeoff_policies, except: [:show, :edit, :update, :new] do
        resources :settings, only: [:show, :update], controller: 'timeoff_policies/settings'
      end
      resources :timeoffs, except: [:destroy], :concerns => :trackable do
        collection do
          get :logs
        end

        member do
          put 'change_status/:status',    action: :change_status,   constraints: { status: /decline|approve|cancel/ }, as: :change_status
          put 'change_assignee/:user_id', action: :change_assignee, as: :change_assignee
        end
      end
      resources :locations, except: [:new, :show]
      resources :teams,     except: [:new, :show]
      resources :employees, except: [:show] do
        collection do
          post :bulk_terminate
          post :bulk_location
          post :bulk_team

          post :import_file
          get  :dashboard
        end
      end
      resources :calendars
      namespace :employees do
        resources :export_imports, only: [:index, :new, :create] do
          collection do
            get :template
          end
        end
      end

      root to: 'employees#dashboard', as: 'company_root'
    end
  end



  # Public domain (www, nil)
  # -----------------------------------------
  # try to use the REST default action, respond_with, location features.
  constraints(PublicConstraint) do
    get 'visitors/tour'
    get 'visitors/pricing'
    get 'visitors/privacy'
    get 'visitors/terms'
    # dummy static page
    get :static_tasks_list,           to: 'visitors#static_tasks_list'
    get :static_show_expense_detail,  to: 'visitors#static_show_expense_detail'
    get :static_show_travel_detail,   to: 'visitors#static_show_travel_detail'
    get :static_show_timeoff_detail,  to: 'visitors#static_show_timeoff_detail'

    namespace :companies do
      get '/sign_up' => 'registrations#new'
      get '/welcome' => 'registrations#index'
      resources :registrations, only: [:create]
      resources :confirmations, only: [:create, :update, :new, :edit]
    end

    mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  end


  # error pages
  get '/500', to: 'errors#internal_server_error', as: 'internal_error'
  get '/404', to: 'errors#not_found',             as: 'not_found'

  # root page
  root to: 'visitors#index'
end

app/controllers/concerns/private/form_entries/destroy_attachment.rb
module Concerns::Private::FormEntries::DestroyAttachment
  extend ActiveSupport::Concern

  # DELETE - destroy_attachment_company_form_entry_path(entry_id, :field_id)
  # required params:
  #  - order: index of attachment, if multiple == 1
  #
  def destroy_attachment
    if field.properties['multiple'] == '1'
      entry.answers[field.id.to_s].delete_at(Integer(params[:index]))
    else
      entry.answers[field.id.to_s] = nil
    end
    entry.skip_process_answers = true
    entry.save

    respond_with [:edit, :company, entry]
  end


  # DELETE - destroy_expense_attachment_company_form_entry_path(entry_id, field_id, row_index, file_index)
  #
  def destroy_expense_attachment
    entry.answers[field.id.to_s][Integer(params[:row_index])]['files'].delete_at(Integer(params[:file_index]))
    entry.skip_process_answers = true
    entry.save

    respond_with [:edit, :company, entry]
  end

end

app/controllers/concerns/private/form_entries/upload_attachment.rb
module Concerns::Private::FormEntries::UploadAttachment
  extend ActiveSupport::Concern


  # # POST - upload_attachment_company_form_entry_path(id, field_id)
  # # require params:
  # #   - file
  # #
  # def upload_attachment
  #   entry.upload_attachment(params[:field_id], params[:file])
  #   respond_with [:company, entry]
  # end

  # POST - upload_expense_attachment_company_form_entry_path(id, field_id, row_index)
  # require params:
  #   - file
  #
  def upload_expense_attachment
    uploaded_url = entry.upload_attachment(params[:field_id], params[:file], {
      row_index: params[:row_index]
    })

    respond_to do |format|
      format.json { render json: { url: uploaded_url } }
    end
  end

end

app/controllers/private/activities_controller.rb
class Private::ActivitiesController < Private::ModuleController
  before_action :set_activity, only: [:show, :edit, :update, :destroy]
  # before_filter :load_trackable
  respond_to :html, :json

  def index
    @activities = PublicActivity::Activity.all
    respond_with(@activities)
  end

  def show
    respond_with(@activity)
  end

  def new
    @trackable = find_trackable
    @activity = PublicActivity::Activity.new( :trackable_id => @trackable.id,
                            :trackable_type => @trackable.class.to_s)
    respond_with(@activity)
  end

  def edit
  end

  def create
    @trackable = find_trackable
    @activity = @trackable.activities.build(activity_params)
    @activity.owner = current_user
    flash[:notice] = 'Comment was successfully created.' if @activity.save
    respond_with([:company, @trackable])
  end

  def update
    flash[:notice] = 'Comment was successfully updated.' if @activity.update(activity_params)
    respond_with(@activity)
  end

  def destroy
    @activity.destroy
    respond_with(@activity)
  end

  def load_trackable(trackable_type,trackable_id)
    @trackable = trackable_type.camelize.constantize.find(trackable_id)
  end

  private
    def set_activity
      @activity = PublicActivity::Activity.find(params[:id])
    end

    def activity_params
      params.require(:public_activity_activity).permit(:key, {:parameters => [:msg]}, :trackable_id, :trackable_type, :owner_id, :owner_type, :recipient_id, :recipient_type)
    end

    def find_trackable
      params.each do |name, value|
        if name =~ /(.+)_id$/
          return "#{$1}".classify.constantize.find(value)
        end
      end
      nil
    end
end

app/controllers/private/admin/billing_address_controller.rb
class Private::Admin::BillingAddressController < Private::Admin::ModuleController
  def update
    begin
      result = Braintree::Address.update(
        current_company.customer_uid, billing_address.id,
        billing_address_params
      )

      if result.success?
        flash[:notice] = "Success update your billing address"
      else
        flash[:alert]  = "Something wrong when update your address detail, please contact out customer support"
      end

    rescue Braintree::NotFoundError => e
      flash[:alert] = e.message

    ensure
      redirect_to company_admin_plan_and_billings_path
    end
  end

  protected

  def billing_address_params
    params.require(:billing_address).permit(:company, :street_address, :locality, :region,
      :country_code_alpha2, :postal_code, :extended_address)
  end

  def billing_address
    @billing_address ||= current_company.braintree_customer.addresses.first
  end
end

app/controllers/private/admin/credit_cards_controller.rb
class Private::Admin::CreditCardsController < Private::Admin::ModuleController

  # POST - company_admin_credit_cards_path
  #
  def create
    current_company.subscription.change_payment_method(params)
    redirect_to company_admin_plan_and_billings_path
  end


  # DELETE - company_admin_credit_card_path(token)
  #
  def destroy
    begin
      result = Braintree::CreditCard.update(
        credit_card.token, credit_card_params
      )

      # TO DO

    rescue Braintree::NotFoundError => e
      flash[:alert] = e.message

    ensure
      redirect_to company_admin_plan_and_billings_path
    end
  end

  protected

  def credit_card_params
    params.require(:credit_card).permit(:cardholder_name, :expiration_month, :expiration_year)
  end

end

app/controllers/private/admin/embedded_forms_controller.rb
class Private::Admin::EmbeddedFormsController < Private::Admin::ModuleController
  # GET - company_admin_embedded_forms_path
  #
  def index
    @user_forms = current_company.embedded_forms.where(klass: 'User')
  end

  # GET - new_company_admin_embedded_form_path
  #
  def new
    @embedded_form = current_company.embedded_forms.new(klass: params[:klass])
  end


  # POST - company_admin_embedded_forms_path
  #
  def create
    @embedded_form = current_company.embedded_forms.new(embedded_form_params)

    if @embedded_form.save
      flash[:notice] = "Success attach form '#{@embedded_form.form.name}' to model #{@embedded_form.klass}"
      redirect_to company_admin_embedded_forms_path
    else
      flash[:error] = @embedded_form.errors.full_messages
                                           .join('<br />')
                                           .html_safe
      render action: :new
    end
  end


  # DELETE - company_admin_embedded_form_path(id)
  #
  def destroy
    embedded_form.destroy
    flash[:notice] = "Success detect dyno-form"
    redirect_to :back
  end

  protected

  def embedded_form_params
    params.require(:embedded_form).permit(:klass, :form_id)
  end

  def embedded_form
    @embedded_form ||= EmbeddedForm.find(params[:id])
  end
end

app/controllers/private/admin/forms_controller.rb
class Private::Admin::FormsController < Private::Admin::ModuleController

  # GET - company_admin_forms_path
  #
  def index
    @forms = current_company.forms
  end

  # GET - new_company_admin_form_path
  #
  def new
    @form = current_company.forms.new
  end

  def create
    @form = current_company.forms.new(form_params)
    if @form.save
      flash[:notice] = 'Success create custom form'
      redirect_to company_admin_forms_path
    else
      flash[:error] = @form.errors.full_messages
                                  .join('<br/>')
                                  .html_safe

      render action: 'new'
    end
  end

  # GET - edit_company_admin_form_path(:id)
  #   id --> (expense, travel, timeoff)
  #
  def edit
    form
  end


  # GET -
  #
  def update
    if form.update_attributes(form_params)
      flash[:notice] = 'Success update custom form'
      redirect_to company_admin_forms_path
    else
      flash[:error] = form.errors.full_messages.join('<br />')
      render action: :edit
    end
  end


  # DELETE - company_admin_form_path(:id)
  #
  def destroy
    form.destroy
    flash[:notice] = 'Success remove form'
    redirect_to company_admin_forms_path
  end

  private

  def form_params
    params.require(:form).permit( :name, :introduction, :icon, :show_on_calendar,
                                  :require_sign, fields_attributes: [:id, :position, :name,
                                    :field_type, :required, :_destroy,
                                    properties: [
                                      :description, :true_label, :false_label, :unremoved,
                                      :label, :hint, :placeholder, :min_number, :max_rows,
                                      :currency,  :add_on, :from_number,  :to_number, :multiple,
                                      :max_rating, :format, :symbol, :max_number, :prompt,
                                      :tax_filling_status_prompt, :tax_decline_with_holding_prompt,
                                      :groups => [:name, :add_on, :add_on_value],
                                      :advance_groups => [
                                        :name, :add_on, :add_on_value, :type, :prompt, options: []
                                      ],
                                      personal_genders: [:label, :value], personal_marital_statuses: [:label, :value],
                                      compensation_currencies: [:label, :value], compensation_periods: [:label, :value],
                                      bank_account_types: [:label, :value],
                                      tax_filling_status_options: [:label, :value], tax_decline_with_holdings: [:label, :value],
                                      currencies: [:label, :value], payments: [:label, :value],
                                      categories: [:label, :value], purposes: [:label, :value],
                                      transportations: [:label, :value], classes: [:label, :value],
                                      select_options: [:label, :value]
                                    ]
                                  ],
                                  approvals_attributes: [:id, :role, :_destroy, :approver_id]
                                )
  end

  def form
    @form ||= current_company.forms.find params[:id]
  end

end

app/controllers/private/admin/module_controller.rb
class Private::Admin::ModuleController < Private::ModuleController
  before_action :authenticate_admin!

  protected

  def authenticate_admin!
    raise Pundit::NotAuthorizedError unless current_user.admin? || current_user.corp_admin?
  end
end

app/controllers/private/admin/plan_and_billings_controller.rb
class Private::Admin::PlanAndBillingsController < Private::Admin::ModuleController
  respond_to :html, :json

  # GET - company_admin_plan_and_billings
  #
  def show
    prepare_data
  end


  # POST - company_admin_plan_and_billings_path
  #
  def create
    # authorize current_subscription
    if current_subscription.purchase!(params)
      flash[:notice] = 'Success change your plan'
      redirect_to company_admin_plan_and_billings_path
    else
      flash[:alert] = if current_subscription.result_errors.present?
                        current_subscription.result_errors
                      else
                        debugger
                        'Something wrong when we change your plan, please try again later'
                      end

      redirect_to :back
    end
  end


  # PUT
  #
  def change_plan
    authorize current_subscription

    begin
      if current_subscription.change_plan!(params)
        flash[:notice] = 'Success change your plan'
      else
        flash[:alert] = if current_subscription.result_errors.present?
                          current_subscription.result_errors
                        else
                          'Something wrong when we change your plan, please try again later'
                        end
      end

    rescue Exceptions::DowngradeMaxEmployeesReached => e
      flash[:alert] = e.message

    ensure
      redirect_to company_admin_plan_and_billings_path
    end
  end


  protected

  def prepare_data
    if current_company.subscription.uid.present?
      @braintree_subscription ||= current_company.subscription.braintree_subscription
    end

    @plan               ||= current_company.subscription.plan
    @braintree_customer ||= current_company.braintree_customer
    @credit_card        ||= @braintree_customer.credit_cards.first
    @billing_address    ||= @braintree_customer.addresses.first
  end

  def billing_address
    @billing_address ||= current_company.braintree_customer.addresses.first
  end

  def current_subscription
    @current_subscription ||= current_company.subscription
  end

  def billing_address_params
    params.require(:billing_address).permit(:company_name, :address, :address2, :city, :zipcode, :country, :state)
  end
end

app/controllers/private/employees/module_controller.rb
class Private::Employees::ModuleController < Private::ModuleController
  # Still nothing todo here
end

app/views/private/timeoffs/_managed_timeoffs.html.erb
<div class="row">
  <div class="col-xs-12">
    <h3>Managed Timeoffs</h3>
    <%= link_to 'New Timeoff', new_company_timeoff_path, class: 'btn btn-primary' %>
    <table class="table table-bordered table-hover">
      <thead>
        <tr>
          <th>No. </th>
          <th>Status</th>
          <th>Cateogry</th>
          <th>Name</th>
          <th>Time</th>
          <th>Description</th>
          <th>Actions</th>
        </tr>
      </thead>

      <tbody>
        <% timeoffs.each_with_index do |timeoff, idx| %>
          <tr>
            <td><%= idx + 1 %></td>
            <td><%= timeoff.status %></td>
            <td><%= timeoff.category %></td>
            <td><%= timeoff.name %></td>
            <td>
              <p>
                From: <%=l timeoff.start_at, format: :custom %>
                <br />
                To: <%=l timeoff.end_at, format: :custom %></td>
              </p>
            <td><%= timeoff.description %></td>
            <td>
              <%= link_to 'Edit', edit_company_timeoff_path(timeoff), class: 'btn btn-xs btn-primary' %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>

  </div>
</div>

app/views/private/timeoffs/_subnav.html.erb
<li <% if(active == "timeoffs") %> class="active"<% end %>><%= link_to t('.link.timeoff'), company_timeoffs_path %></li>
<li <% if(active == "timeoff_logs") %> class="active"<% end %>><%= link_to t('.link.timeoff_logs'), logs_company_timeoffs_path %></li>

app/views/private/timeoffs/index.html.erb
<% content_for :subnav do %>
  <div class="subnav">
    <ul>
      <%= render 'subnav', active: 'timeoffs' %>
    </ul>
  </div>
<% end %>

<div class="pages tasks" ng-cloak="true" ng-controller="TimeoffIndexCtrl">

  <div class="page-title">
    <h1 class="pull-left"><%= t('.Timeoffs') %></h1>
    <%= link_to 'New Timeoff', new_company_timeoff_path, class: 'pull-right btn btn-lg btn-primary' %>

    <% if policy(current_user.timeoffs.new(timeoff_type: 'custom')).new? %>
      <%= link_to 'Custom Timeoff', new_company_timeoff_path(type: 'custom'), class: 'pull-right btn btn-lg btn-warning mr10' %>
    <% end %>
  </div>

  <div class="action-menu">
    <ul class="pull-left">
      <li>
        <%= link_to company_timeoffs_path(sort: params[:sort]) do %>
          <%= t('.all') %>
          <span class='badge badge-default'><%= @all_timeoffs.to_a.size %></span>
        <% end %>
      </li>

      <li>
        <%= link_to company_timeoffs_path(type: 'managed', sort: params[:sort]) do %>
          <%= t('.managed_timeoffs') %>
          <span class='badge badge-default'><%= @all_timeoffs.author_by(current_user.id).to_a.size %></span>
        <% end %>
      </li>

      <li>
        <%= link_to company_timeoffs_path(type: 'assigned', sort: params[:sort]) do %>
          <%= t('.assigned_timeoffs') %>
          <span class='badge badge-default'><%= @all_timeoffs.assigned_to(current_user.id).to_a.size %></span>
        <% end %>
      </li>

      <li ng-class="activeYourTimeoffs">
        <%= link_to company_timeoffs_path(type: 'owner', sort: params[:sort]) do %>
          <%= t('.your_timeoffs') %>
          <span class='badge badge-default'><%= @all_timeoffs.owner_by(current_user.id).to_a.size %></span>
        <% end %>
      </li>

      <!-- <li>
        <%= link_to company_timeoffs_path(type: 'owner', status: 'approved', sort: params[:sort]) do %>
          <%= t('.used_timeoffs') %>
          <span class='badge badge-default'><%= @all_timeoffs.owner_by(current_user.id).with_status(:approved).to_a.size %></span>
        <% end %>
      </li> -->
    </ul>

    <ul class="pull-right">
      <li class="dropdown">
        <%= link_to raw("#{t('.sort')} <i class='pi pi-arrow-drop-down'></i>"), '#', class: 'dropdown-toggle' %>
        <div class="dropdown-menu">
          <div class="arrow"></div>
          <ul>
            <li>
              <%= link_to t('.by_author'), company_timeoffs_path(type: params[:type], sort: 'author') %>
            </li>

            <li>
              <%= link_to t('.by_assignee'), company_timeoffs_path(type: params[:type], sort: 'assignee') %>
            </li>

            <li>
              <%= link_to t('.by_date'), company_timeoffs_path(type: params[:type], sort: 'date') %>
            </li>

            <li>
              <%= link_to t('.by_status'), company_timeoffs_path(type: params[:type], sort: 'status') %>
            </li>

            <li>
              <%= link_to t('.by_name'), company_timeoffs_path(type: params[:type], sort: 'name') %>
            </li>
          </ul>
        </div>
      </li>
    </ul>
  </div>

  <div class="row">
    <div class="col-md-12" id="list-task">
      <% @timeoffs.each do |timeoff| %>
        <!-- Start Block -->
        <div class="block block-default list-block">
          <div class="block-body">
            <%= link_to company_timeoff_path(timeoff), class: 'link-wrapper' do %>
              <span class="circle-icon icon-money"></span>
              <h4 class="block-title">
                <%= timeoff.name %>
                <span class="label label-<%= timeoff.status%>"><%= timeoff.status %></span>
              </h4>
              <span class="list-desc">
                <% if timeoff.start_at.present? && timeoff.end_at.present? %>
                  <%=l timeoff.start_at, format: :custom %>
                  to
                  <%=l timeoff.end_at, format: :custom %>
                <% end %>
              </span>
              <div class="attributes">
                <span am-time-ago="task.created_at"><i class="pi pi-clock"></i><%= time_ago_in_words(timeoff.created_at) %> ago</span>
                <span><i class="pi pi-person"></i> <%= t('.submitted_by')%> <%= timeoff.author.try(:name) || 'By System'  %>.</span>

                <% if timeoff.assignee.present? %>
                  <span><i class="pi pi-person"></i> <%= t('.assigned_to')%> <%= timeoff.assignee.try(:name) || 'By System' %>.</span>
                <% end %>

                <% if timeoff.timeoff_type_manual? %>
                  <span><i class="pi pi-person"></i> <%= t('.request_for')%> <%= timeoff.user.name %>.</span>
                <% end %>
              </div>
            <% end %>
          </div>
        </div>
        <!-- // End Block -->
      <% end %>
    </div>
  </div>
</div>

app/views/private/timeoffs/new.html.erb
<div ng-controller="TimeoffNewCtrl">
  <div class="sticky-header">
    <div class="content-wrapper">
      <div class="breadcrumb">
        <%= link_to raw("<i class='pi pi-arrow-back'></i> #{t('.back_to_tasks')}"), company_timeoffs_path %>
      </div>
    </div>
  </div>



  <div class="pages tasks">
    <div class="heading">
      <span class="circle-icon icon-suitcase"></span>
      <h2>New Timeoff Log</h2>
    </div>
    <!-- render chart -->
    <%= render 'charts', user: @user %>
    <!-- Task Detail Partials -->
    <%= render 'form', timeoff: @timeoff %>
    <!-- End Task Detail Partials -->
  </div>
</div>

<%= call_js_init("stickyHeader();") %>

app/views/private/timeoffs/show.html.erb
<div ng-controller="TimeoffNewCtrl">
  <div class="sticky-header">
    <div class="content-wrapper">
      <div class="breadcrumb">
        <%= link_to raw("<i class='pi pi-arrow-back'></i> #{t('.back_to_timeoffs')}"), company_timeoffs_path %>
      </div>
      <div class="page-actions">
        <% if policy(@timeoff).change_status? %>
          <%= link_to t('.approve'), change_status_company_timeoff_path(@timeoff, 'approve'), class: "btn btn-sm btn-primary", method: :put %>
          <%= link_to t('.decline'), change_status_company_timeoff_path(@timeoff, 'decline'), class: "btn btn-sm btn-warning", method: :put, data: { confirm: 'Are you sure to decline this timeoff?' } %>
        <% end %>

        <% if @timeoff.status_approved? %>
          <%= link_to change_status_company_timeoff_path(@timeoff, 'cancel'), class: "btn btn-sm btn-warning", method: :put, data: { confirm: "Are you sure to cancel this timeoff request?" } do %>
            <%= t('.cancel') %>
          <% end %>
        <% end %>

        <% if policy(@timeoff).change_assignee? %>
          <div class="dropdown">
            <%= link_to 'javascript:void', class: 'btn btn-sm btn-secondary dropdown-toggle', id: 'dropAssignee' do  %>
               <%= t('.assign_to') %>
               <span class="caret"></span>
            <% end %>
            <ul class="dropdown-menu" role="menu" aria-labelledby="dropAssignee">
              <% current_company.users.where("users.id != ?", @timeoff.assignee_id).each do |user| %>
                <li role="presentation">
                  <%= link_to user.name, change_assignee_company_timeoff_path(@timeoff, user), method: :put, data: { confirm: "Are you sure assign this Timeoff Request to #{user.name}?" } %>
                </li>
              <% end %>
            </ul>
          </div>
        <% end %>
      </div>
    </div>
  </div>

  <div class="pages tasks">
    <div class="heading">
      <span class="circle-icon icon-suitcase"></span>
      <% if policy(@timeoff).update? %>
        <%= link_to edit_company_timeoff_path(@timeoff), class: "link-gray pull-right link-edit" do %>
          <i class='pi pi-edit'></i>
          <%= t('.edit') %>
        <% end %>
      <% end %>
      <h2><%= @timeoff.name %></h2>

      <% if @timeoff.memo.present? %>
        <span class="task-detail-description"><%= @timeoff.memo %></span>
      <% end %>

      <% if @timeoff.timeoff_type_manual? %>
        <span class="task-detail-duration">
          <%=l @timeoff.start_at, format: :short %>
          to
          <%=l @timeoff.end_at, format: :short %>
        </span>
        <br>
      <% elsif @timeoff.timeoff_type_custom? %>
        <span class="task-detail-duration">
          <%= @timeoff.amount.to_i %>
          hours additional for
          <%= @timeoff.category.name %>
        </span>
        <br>
      <% end %>

      <h4 class="status-label">
        <span class="label label-<%= @timeoff.status%>"><%= @timeoff.status %></span>
      </h4>

      <div class="attributes">
        <span>
          <i class="pi pi-clock"></i>
          <%= time_ago_in_words(@timeoff.created_at) %> ago
        </span>

        <% if @timeoff.timeoff_type_manual? %>
          <span>
            <i class="pi pi-person"></i>
            <%= t('.submitted_by') %>
            <%= link_to @timeoff.author.name, '#' %>
          </span>

          <% if @timeoff.assignee.present? %>
            <span>
              <i class="pi pi-person"></i>
              <%= t('.assigned_to') %>
              <%= link_to @timeoff.assignee.name, '#' %>
            </span>
          <% end %>

          <span>
            <i class="pi pi-person"></i>
            <%= t('.request_for') %>
            <%= link_to @timeoff.user.name, '#' %>
          </span>
        <% end %>
      </div>

      <% if @timeoff.attachments.present? %>
        <div class="attributes">
          <span>
            <i class="fa fa-file"></i>
            &nbsp;
            Attachments:
          </span>

          <% @timeoff.attachments.each do |attachment| %>
            <span><%= link_to attachment.file.filename, attachment.url, target: :blank %></span>
          <% end %>
        </div>
      <% end %>
    </div>
    <!-- End Request for Time Off -->

    <!-- render chart -->
    <%= render 'charts', user: @user %>


    <!-- End Task Detail Partials -->
    <div class="page-activities">
      <h2>Activities</h2>
      <div class="row">
        <div class="col-xs-10 col-xs-offset-2">
          <div class="activities">
            <%= render :partial => 'public_activity/form', locals: {trackable_type:@timeoff.class.to_s, trackable_id:@timeoff.id } %>
            <div class="activities-msg">
              <%= render_activities(@timeoff.activities.order(created_at: :desc), layout: :activity) %>
            </div>

            <div class="text-center">
              <button class="btn btn-md btn-secondary show-more" type="button">Show 3 Older Activities</button>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<%= call_js_init("stickyHeader();") %>